Initial commit of Aleph provider with working login. BBS-13
rvk-utd/ding2 pull request #1
Opened 2017-06-12 12:55 UTC by tripox

2017-06-15 13:27 UTC, danquah requested changes

2017-06-15 13:27 UTC, danquah commented on modules/aleph/aleph.install
> +  if ($phase == 'runtime') {
Have you tested that the site can still be installed and that it is possible to select the aleph provider during installation?

2017-06-15 13:27 UTC, danquah commented on modules/aleph/aleph.info
> +dependencies[] = virtual_field
I suspect that we have dependencies on modules we dont need right now on this list, but lets check it when we get a bit further and know what we actually need.

2017-06-15 13:27 UTC, danquah commented on modules/aleph/aleph.module
> +      $client = new AlephClient(variable_get('aleph_base_url', 'http://snorri.lb.is/X'));
Think we should assume the variable is set, and fail if it is not - the variable can be set during installation, and for development-purposes we could set it in docker.settings.php

2017-06-15 13:27 UTC, danquah commented on modules/aleph/includes/aleph.user_consent.inc
> + * When a user gives permission to store his or her loan history for longer
The documentation should reflect that we hardcode the consent on purpose.

2017-06-15 13:27 UTC, danquah commented on modules/aleph/includes/aleph.user_consent.inc
> + * Update the user consent.
We should probably also document pr. method why we hardcode the response

2017-06-15 13:27 UTC, danquah commented on modules/aleph/lib/AlephClient/AlephClient.class.php
> +require __DIR__ . '../../../vendor/autoload.php';
We need to be 100% on how we autoload classes if we have more than one than one autoload.php in play (we might be good, and might be in trouble)

2017-06-16 10:44 UTC, tripox commented on modules/aleph/lib/AlephClient/AlephClient.class.php
> +require __DIR__ . '../../../vendor/autoload.php';
```grep -r 'guzzle' .``` in the root shows that guzzle is used in two modules and then theres a library (I removed some of the output for convenience):

```
./web/profiles/ding2/modules/fbs/composer.json:        "guzzlehttp/guzzle": "5.2.0"
./web/profiles/ding2/modules/aleph/composer.json:        "guzzlehttp/guzzle": "^6.2"
./web/profiles/ding2/modules/bpi/lib/bpi-client/composer.json:        "guzzlehttp/guzzle": "^6.2"
./web/profiles/ding2/ding2.make:libraries[guzzle][download][tag] = "6.2.2"
./web/profiles/ding2/ding2.make:libraries[guzzle][destination] = "libraries"
./web/profiles/ding2/ding2.make:libraries[promises][download][url] = "https://github.com/guzzle/promises.git"
./web/profiles/ding2/ding2.make:libraries[psr7][download][url] = "https://github.com/guzzle/psr7.git"
```

2017-06-16 10:47 UTC, tripox commented on modules/aleph/aleph.info
> +dependencies[] = virtual_field
I agree. :)

2017-06-16 10:59 UTC, tripox commented on modules/aleph/aleph.module
> +      $client = new AlephClient(variable_get('aleph_base_url', 'http://snorri.lb.is/X'));
I agree. I've set the variable in `docker.settings.php`: https://github.com/reload/ding-docker/commit/100cc7c240750ae7c15ac919b6ba692cb732ed07 and removed the default variable here: https://github.com/rvk-utd/ding2/pull/1/commits/895819b7d4556ea467be67ff8efc3dac36af1261.

2017-06-16 11:11 UTC, tripox commented on modules/aleph/includes/aleph.user_consent.inc
> + * When a user gives permission to store his or her loan history for longer
https://github.com/rvk-utd/ding2/pull/1/commits/8aeb4f0c3635aa0042b3e4100c2a74ee829fc88a

2017-06-16 11:11 UTC, tripox commented on modules/aleph/includes/aleph.user_consent.inc
> + * Update the user consent.
https://github.com/rvk-utd/ding2/pull/1/commits/8aeb4f0c3635aa0042b3e4100c2a74ee829fc88a

2017-06-16 11:11 UTC, tripox commented on modules/aleph/aleph.install
> +  if ($phase == 'runtime') {
I will try now.

2017-06-16 11:14 UTC, tripox commented
@danquah, I'll nudge you, when I've tried to run the installation.

2017-06-16 13:26 UTC, tripox commented on modules/aleph/aleph.install
> +  if ($phase == 'runtime') {
Works perfectly. Added patch to show provider when installing profile.
https://github.com/rvk-utd/ding2/pull/1/commits/70d7fc82b21ad7fd4aac43fc4faf99396d5b37fd

2017-06-16 13:51 UTC, danquah commented on modules/aleph/lib/AlephClient/AlephClient.class.php
> +require __DIR__ . '../../../vendor/autoload.php';
👍

2017-06-16 13:51 UTC, danquah commented on modules/aleph/includes/aleph.user_consent.inc
> + * Update the user consent.
Would be nice with a comment pr function that makes a static return.

2017-06-16 13:53 UTC, danquah commented on modules/aleph/includes/aleph.user_consent.inc
> + * When a user gives permission to store his or her loan history for longer
👍

2017-06-16 13:53 UTC, danquah commented on modules/aleph/aleph.info
> +dependencies[] = virtual_field
👍

2017-06-16 13:53 UTC, danquah commented on modules/aleph/aleph.install
> +  if ($phase == 'runtime') {
👍

2017-06-16 18:09 UTC, danquah approved these changes
![](https://media1.giphy.com/media/11sBLVxNs7v6WA/giphy.gif)

2017-06-19 07:31 UTC, merged