Port ting_new_materials to SAL. BBS-177
rvk-utd/ding2 pull request #100
Opened 2017-11-24 12:01 UTC by tripox

2017-11-24 12:04 UTC, tripox commented on modules/ting_new_materials/ting_new_materials.module
> +      ->addSort('date', 'descending')
Should this be `->addSort('date_descending', 'descending')`?

2017-11-24 13:27 UTC, kasperg requested changes
Reviewed. I have some comments.

2017-11-24 13:27 UTC, kasperg commented on modules/ting_new_materials/ting_new_materials.module
> +      ->addFieldFilter('collectionType', 'manifestation');
As mentioned in another PR: Are `enrich` and `collectionType` valid field filters?

2017-11-24 13:27 UTC, kasperg commented on modules/ting_new_materials/ting_new_materials.module
> + * @return TingSearchResultInterface
This does not seem right. Obviously the return type of this method changes but I would expect that all the callers needs to be updated as well to use the methods provided by the new interface.

2017-11-27 12:39 UTC, tripox commented
@kasperg, do you know what 'collectionType' is and why it's set to: 'manifestation'?
Should we support it?

2017-11-28 08:12 UTC, kasperg commented
In short `collectionType=` will make OpenSearch behave as if all collections only contain a single object. In Ding2 this is the same behavior as a search provider which does not support collections would have.

There is more information in [the documentation](https://opensource.dbc.dk/services/open-search-web-service) under the headline Work structure.

2017-11-30 13:58 UTC, kasperg approved these changes

2017-11-30 13:59 UTC, merged