Feature/bbs 178 port ting search carousel to sal
rvk-utd/ding2 pull request #110
Opened 2017-11-29 14:53 UTC by tripox

2017-11-30 09:38 UTC, kasperg requested changes
Reviewed. I have bunch of questions and comments.

2017-11-30 09:38 UTC, kasperg commented on modules/opensearch/includes/opensearch.search.inc
> +  // to handle the filter differently query_parts is empty.
I really appreciate the comment but I do not see how it is implemented. I would have expected a check whether `$query_parts` is `empty()` or not.

Either the comment is no longer relevant and should be removed or the subsequent code needs to be updated.

2017-11-30 09:38 UTC, kasperg commented on modules/ting_search_carousel/ting_search_carousel.module
> +  $collections = $results->getTingEntityCollections();
I would expect `$results->getTingEntityCollections()` to be moved to `L305`.

The check on `L297` does not make any sense if we already assume on `L294` that the return value from `$sal_query->execute()` is a proper object.

2017-11-30 09:38 UTC, kasperg commented on modules/opensearch/includes/opensearch.search.inc
> +      $query_parts[] = '* NOT ' . implode(' NOT ', $material_filter);
Nice level of commenting here.

2017-11-30 09:38 UTC, kasperg commented on modules/ding_provider/tests/ding_provider_implementation.test
> +    $this->assertTrue($query->isMaterialFilterInclude());
Would it be possible to extend the test with a case where the material filter is exclude?

2017-11-30 15:37 UTC, tripox commented
Done.
@kasperg added test but was not able to run it.
Running tests takes forever on my machine.

2017-12-06 12:25 UTC, kasperg commented
@tripox: Tests fail 😢 

`Fatal error: Call to undefined method Connie\Search\ConnieSearchResult::setMaterialFilter() in /tmp/drupal/profiles/ding2/modules/ding_provider/tests/ding_provider_implementation.test on line 598`

2017-12-08 14:45 UTC, danquah approved these changes
![](https://media3.giphy.com/media/3HAYjf986boJO698zIY/200w.gif?cid=5a38a5a25a2aa57d634d706b2eb4eb41)

2017-12-08 15:05 UTC, merged