Fix handling of location scope.
rvk-utd/ding2 pull request #113
Opened 2017-11-30 17:07 UTC by tripox

The log was spammed with errors because the `locationScope` property was given an array.
Primo doesn't like "Array" in the query. 😉

2017-12-01 12:19 UTC, kasperg requested changes
I think this is the wrong way to go about this. Either it should be a string or an array.

Based on the convertation in #108 I think we should update the variable setting script instead.

2017-12-01 14:58 UTC, tripox commented
@kasperg, I fixed the default value. :)

2017-12-06 12:26 UTC, kasperg approved these changes

2017-12-06 12:26 UTC, kasperg commented
@tripox: :+1: LGTM

2017-12-06 12:38 UTC, merged