Continuous Integration setup
rvk-utd/ding2 pull request #12
Opened 2017-07-11 07:45 UTC by danquah

BBS-53

2017-07-18 08:21 UTC, kasperg requested changes
Reviewed.

These changes partly duplicate [what has already been merged to master](https://github.com/ding2/ding2/pull/627/files).

It may be useful for us to cherry pick that commit and then added what is missing from this PR on top.

2017-07-18 08:21 UTC, kasperg commented on modules/ding_test/ding_test.module
> -function ding_test_xautoload($adapter) {
According to [Drupal Code standards](https://www.uptrends.com/) we should not user fully qualified class names in the code but add a `use` statement at the top of the file instead.

2017-07-18 08:21 UTC, kasperg commented on drupal.make
> +projects[ding2][patch][] = ding-core-patches/bpi-nullable-primary-key.patch
I am not very keen on patching our own code. Why not just make the change?

2017-07-18 08:21 UTC, kasperg commented on ding2.make
> +projects[dibs][patch][2812891] = "https://www.drupal.org/files/issues/mysql_5.7_compatibility-2812891-2.patch"
In general patches should include a comment about why the patch is needed.

2017-07-18 08:21 UTC, kasperg commented on ding2.make
> +projects[message][patch][2051751] = "https://www.drupal.org/files/message-primary_nullable-2051751-7.patch"
As above.

2017-07-18 08:21 UTC, kasperg commented on .scrutinizer.yml
> +        - modules/ding_tabroll/js/jquery-ui-tabs-rotate*.js
:+1:

This should be upstreamed and libraries preferably downloaded via Drush Make and loaded via Libraries API. That is perhaps outside the scope of this PR.

2017-07-18 08:21 UTC, kasperg commented on Makefile
> +	patch -p1 < ding-core-patches/bpi-nullable-primary-key.patch
This can be removed if we apply the changes directly.

2017-07-18 08:21 UTC, kasperg commented on Makefile
> +	# Tests to be run are referenced as a comma-seperated list of group-names.
:+1:

2017-07-18 08:21 UTC, kasperg commented on circle.yml
> +    version:  5.6.17
I would prefer just to make the change instead of having an outcommented configuration value.

2017-07-18 08:57 UTC, danquah commented on drupal.make
> +projects[ding2][patch][] = ding-core-patches/bpi-nullable-primary-key.patch
I'm good with that, did it mostly in case this was done upstream before we get to merging our changes.

2017-07-18 09:25 UTC, danquah commented
As implementing some of the suggested changes required a rebase, i've opened up a new PR with the suggested changes implementer over at #14

2017-07-19 06:19 UTC, danquah commented
Closing as we merged an updated version of this branch in #14

2017-07-19 06:19 UTC, closed without merging