Don't strip series number from series description. BBS-190
rvk-utd/ding2 pull request #152
Opened 2018-01-10 15:56 UTC by tripox

2018-01-10 16:01 UTC, tripox commented
@kasperg, I couldn't find a ting object with this data. Do you know of an example?

2018-01-11 15:39 UTC, kasperg requested changes

2018-01-11 15:39 UTC, kasperg commented on modules/primo/src/Primo/Ting/ObjectMapper.php
> +    return $this->document->getSeriesData();
If we do not have any special processing we should just pass the value from the document to the object directly in the `map` function.

2018-01-16 09:07 UTC, danquah approved these changes
![](https://media3.giphy.com/media/LcYPC0SOSZYdO/200w.gif?cid=5a38a5a25a5dc0c5795061336f890462)

2018-01-16 11:35 UTC, merged