Feature/bbs 14 blocked users
rvk-utd/ding2 pull request #2
Opened 2017-06-19 07:32 UTC by tripox

2017-06-19 09:41 UTC, danquah requested changes
Almost there :)

2017-06-19 09:41 UTC, danquah commented on modules/aleph/lib/AlephClient/AlephClient.class.php
> +      // Check if the user is blocked.
One extra line of comment here noticing that this is ids for sub libraries would be nice

2017-06-19 09:41 UTC, danquah commented on modules/aleph/lib/AlephClient/AlephClient.class.php
> +      // Loop through denlinq-1, denlinq-2, denlinq-3.
Just "sub libraries" otherwise you have to update the comment each time you alter the list

2017-06-20 08:56 UTC, tripox commented
Fixed, @danquah 😊

2017-06-20 09:05 UTC, danquah approved these changes
![](https://media0.giphy.com/media/nLH7f5K1Tb1sY/200w.gif)

2017-06-20 09:55 UTC, merged