Implement availablilty items/holdings. BBS-28 BBS-29
rvk-utd/ding2 pull request #28
Opened 2017-08-22 08:32 UTC by tripox

2017-08-22 19:02 UTC, danquah requested changes

2017-08-22 19:02 UTC, danquah commented on modules/aleph/includes/aleph.availability.inc
> + *   Array of ting object ids (faust).
is it called faust in Aleph?

2017-08-22 19:02 UTC, danquah commented on modules/aleph/includes/aleph.availability.inc
> +      if (array_key_exists($item->getSubLibraryCode(), $sub_libraries)) {
No chance of getSubLibraryCode() returning null?

2017-08-22 19:02 UTC, danquah commented on modules/aleph/src/Aleph/AlephMaterial.php
> +   * @return string
Consider adding examples from real data in the description of all the non-trivial getters. It is a bit of work, but very much worth it for the next person who looks at using the getter.

2017-08-22 19:02 UTC, danquah commented on modules/aleph/includes/aleph.availability.inc
> +          // Reference count not available in Aleph.
What is a reference-count?

2017-08-22 19:02 UTC, danquah commented on modules/aleph/src/Aleph/AlephMaterial.php
> +  public static function materialFromItem(\SimpleXMLElement $item) {
Should we add some example xml-documents to the repo? Or maybe just include examples in the source-code? It is very hard to form an opinion on whether $item->xpath('z30/z30-sub-library')[0]); is the best way to query for the data or not ...

2017-08-24 09:25 UTC, tripox commented on modules/aleph/includes/aleph.availability.inc
> +          // Reference count not available in Aleph.
Not sure, but there's nothing like it available in Aleph and they didn't seem to know what it was and not all providers implements it.

2017-08-24 12:15 UTC, danquah approved these changes
No idea why those tests are suddenly failing - the commits leading up to them failing does not seem to be related, so approving
![](https://media1.giphy.com/media/26FxGPtjnVeS6qiJ2/200w.gif)

2017-08-24 12:20 UTC, merged