Implement primo_search_object_ids().
rvk-utd/ding2 pull request #88
Opened 2017-11-17 09:53 UTC by tripox

2017-11-17 20:29 UTC, kasperg requested changes

2017-11-17 20:29 UTC, kasperg commented on modules/primo/includes/primo.search.inc
> +  if (is_array($ids) && !empty($ids)) {
I do not think the `empty()` check is needed here. If the array of ids is empty then we return an empty array of ids back.

2017-11-17 20:29 UTC, kasperg commented on modules/primo/primo.module
> +    '#description' => t('Relevant for looking up objects based on material doc-number.'),
Could we come up with a better name/description for this?

Is it in fact the Primo source id which combined with the object local id is used to construct the Primo record id.

This XML snippet shows some of the Primo elements in effect:

```xml
<control>
  <sourcerecordid>001046847</sourcerecordid>
  <sourceid>ICE01_PRIMO_TEST</sourceid> 
  <recordid>ICE01_PRIMO_TEST001046847</recordid> 
  <originalsourceid>ICE01</originalsourceid> 
  <ilsapiid>ICE01001046847</ilsapiid> 
  <addsrcrecordid>9789979657101</addsrcrecordid> 
  <sourceformat>MARC21</sourceformat> 
  <sourcesystem>Aleph</sourcesystem> 
</control>
```

2017-11-17 20:29 UTC, kasperg commented on modules/primo/includes/primo.search.inc
> +  return FALSE;
Is returning `FALSE` appropriate as a fallback?

2017-11-17 20:29 UTC, kasperg commented on modules/primo/includes/primo.search.inc
> +  if (is_numeric($ids)) {
I do not think `is_numeric()` is an appropriate check. It may work for Aleph but other (theoretical) library systems working with Primo might have strings as ids. The main difference here is that the parameter is a singular value - not an array.

2017-11-20 08:48 UTC, tripox commented on modules/primo/primo.module
> +    '#description' => t('Relevant for looking up objects based on material doc-number.'),
`sourceid` would make sense, I think. :) 
Good point.

2017-11-20 08:49 UTC, tripox commented on modules/primo/includes/primo.search.inc
> +  return FALSE;
OpenSearch does this so I took it directly to be sure.

2017-11-20 08:52 UTC, tripox commented on modules/primo/primo.module
> +    '#description' => t('Relevant for looking up objects based on material doc-number.'),
I took the code from OpenSearch and just removed OpenSearch specific things, just to be sure.
`$ids` can be an array or a string but I agree.
It should only take an array and return an empty array if there's nothing.

2017-11-20 14:27 UTC, kasperg commented on modules/primo/includes/primo.search.inc
> +  return FALSE;
:+1:

2017-11-20 14:31 UTC, kasperg commented on modules/primo/primo.module
> +    '#description' => t('Relevant for looking up objects based on material doc-number.'),
:+1:

2017-11-20 14:46 UTC, tripox commented on modules/primo/includes/primo.search.inc
> +  if (is_numeric($ids)) {
is_numeric() does actually return true on both integers and strings as long as it only contains a numeric string.

2017-11-21 08:44 UTC, kasperg approved these changes
:+1: LGTM. 

Remember to set a default value in our scripts at https://github.com/reload/ding-docker.

2017-11-21 08:46 UTC, merged

2017-11-21 08:58 UTC, tripox commented
@kasperg [the variable is set now.](https://github.com/reload/ding-docker/pull/15) :)