Port raw queries to SAL and fix carousel. BBS-174
rvk-utd/ding2 pull request #97
Opened 2017-11-23 16:07 UTC by tripox

Before merging this, I think we need to fix the cache.
Otherwise the front page will load the first time and die as soon as the requests are cached.

We also need to get verification from Asta if we should use raw queries, full text search or a combined solution.

2017-11-24 13:20 UTC, kasperg requested changes
Reviewed. I have some comments.

2017-11-24 13:20 UTC, kasperg commented on modules/primo/includes/primo.search.inc
> +    $translated_ids[$ids] = variable_get('primo_sourceid') . $ids;
:+1:

Another problem that could have been caught more easily with `array_map()` instead of `foreach` 😉 .

2017-11-24 13:20 UTC, kasperg commented on modules/ting_search_carousel/ting_search_carousel.module
> +    ->setMaterialFilter($ignore);
This does not seem right. 

1. Are `enrich` and `allObjects` actual fields?
2. According to the DocBlock `$ignore` is "Material ids to skip". `setMaterialFilter()` is material ids to include.

2017-11-24 13:20 UTC, kasperg commented on modules/ting_search_carousel/ting_search_carousel.module
> +  $collections = $results->getTingEntityCollections();
Do we need to extract collections this early? As I see it we might as well put it in the `foreach` on L306:

`foreach ($results->getTingEntityCollections() as $collection) {`

2017-11-27 13:24 UTC, tripox commented
@kasperg I removed everything related to ting_search_carousel from this.

2017-11-27 13:32 UTC, kasperg approved these changes

2017-11-27 13:33 UTC, kasperg commented
But if we do not port `ting_search_carousel` then we have no "easy" way of demoing this :\.

2017-11-27 13:42 UTC, tripox commented
I put it in a separate branch. :)

2017-11-27 13:42 UTC, merged